# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "serialport" # TODO: It must be include ladder_deive's dependency.
gem "ladder_drive"
